// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "nextint": {
      name: "nextint",
      type: "registry:example",
      registryDependencies: ["nav","lang-switch","photos"],
      files: ["registry/default/example/next-int/next-int.tsx","registry/default/example/next-int/navbar.tsx","registry/default/example/next-int/lang-switch.tsx","registry/default/example/next-int/photos.tsx"],
      component: React.lazy(() => import("@/registry/default/example/next-int/next-int.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "biophilic-01": {
      name: "biophilic-01",
      type: "registry:example",
      registryDependencies: ["hero"],
      files: ["registry/default/example/biophilic-01/page.tsx","registry/default/example/biophilic-01/components/hero.tsx"],
      component: React.lazy(() => import("@/registry/default/example/biophilic-01/page.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "utils": {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
