// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "hero-01": {
      name: "hero-01",
      description: "Ideal for product designers.",
      type: "registry:block",
      registryDependencies: ["nav","lang-switch","photos"],
      files: [{
        path: "registry/default/blocks/next-int/page.tsx",
        type: "registry:page",
        target: "app/page.tsx"
      },{
        path: "registry/default/blocks/next-int/components/navbar.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/next-int/components/lang-switch.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/next-int/components/photos.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["hero"],
      component: React.lazy(() => import("@/registry/default/blocks/next-int/page.tsx")),
      source: "__registry__/default/blocks/next-int/page.tsx",
      meta: undefined,
    },
    "portofolio-01": {
      name: "portofolio-01",
      description: "minimal portfolio template design for professionals.",
      type: "registry:block",
      registryDependencies: ["footer","list"],
      files: [{
        path: "registry/default/blocks/portofolio-01/main.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/blocks/portofolio-01/components/footer.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/portofolio-01/components/list.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/portofolio-01/components/animated-background.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/portofolio-01/contents/projects.ts",
        type: "registry:file",
        target: "app/data.ts"
      }],
      categories: ["portofolio"],
      component: React.lazy(() => import("@/registry/default/blocks/portofolio-01/main.tsx")),
      source: "__registry__/default/blocks/portofolio-01/main.tsx",
      meta: undefined,
    },
    "portofolio-02": {
      name: "portofolio-02",
      description: "minimal portfolio template design for professionals.",
      type: "registry:block",
      registryDependencies: ["footer","list"],
      files: [{
        path: "registry/default/blocks/portofolio-02/main.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/blocks/portofolio-02/components/bio-detail.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/portofolio-02/components/bio.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/portofolio-02/components/career-path.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/portofolio-02/components/highlight.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/portofolio-02/components/intro-item.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/portofolio-02/components/panel.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/portofolio-02/components/typhography.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/portofolio-02/data/career-path.ts",
        type: "registry:file",
        target: "data/career-path.ts"
      },{
        path: "registry/default/blocks/portofolio-02/data/USER.ts",
        type: "registry:file",
        target: "data/USER.ts"
      },{
        path: "registry/default/blocks/portofolio-02/type/career-path.ts",
        type: "registry:file",
        target: "type/career-pat.ts"
      }],
      categories: ["portofolio"],
      component: React.lazy(() => import("@/registry/default/blocks/portofolio-02/main.tsx")),
      source: "__registry__/default/blocks/portofolio-02/main.tsx",
      meta: undefined,
    },
    "hero-02": {
      name: "hero-02",
      description: "Designed for library applications.",
      type: "registry:block",
      registryDependencies: ["banner","colorfulButton","githubButton","openSource"],
      files: [{
        path: "registry/default/blocks/tool-01/main.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/blocks/tool-01/style/style.css",
        type: "registry:page",
        target: "app/style.css"
      },{
        path: "registry/default/blocks/tool-01/components/header.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/tool-01/components/banner.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/tool-01/components/colorful-button.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/tool-01/components/github-button.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/tool-01/components/installer.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/tool-01/components/open-source.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/tool-01/components/review.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["hero"],
      component: React.lazy(() => import("@/registry/default/blocks/tool-01/main.tsx")),
      source: "__registry__/default/blocks/tool-01/main.tsx",
      meta: undefined,
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      meta: undefined,
    },
  },
}
